In [40]:
import numpy as np
import scipy
from scipy.stats import skew

In [2]:
a1=np.array([20,30,40])

dimension of array

In [ ]:
a1.ndim

check datatype of array

In [4]:
a1.dtype

dtype('int32')

In [5]:
a1.shape

(3,)

In [7]:
a1.size

3

In [8]:
a1.itemsize

4

In [9]:
b=np.array([[1,2,3],[4,5,6]])

In [10]:
b

array([[1, 2, 3],
       [4, 5, 6]])

#arrange

In [12]:
np.arange(10,20,2)

array([10, 12, 14, 16, 18])

linspace

In [13]:
np.linspace(1,2,5)

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [15]:
np.array(np.random.randn(5),dtype='int')

array([ 0,  0, -1, -1,  1])

In [16]:
np.arange(10,20).reshape(5,2)

array([[10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [3]:
a=np.random.randn(24).reshape(2,3,4)
a

array([[[-1.91678594, -0.26056522, -0.21761523, -1.77213407],
        [-0.56462813,  0.52176686, -0.04791242, -0.82589277],
        [ 0.33736462, -0.57359265, -0.6749347 ,  1.53134561]],

       [[-0.445758  ,  0.58182578, -0.52605363,  1.14847863],
        [ 0.74833769, -0.11829136, -1.02358108,  0.34651824],
        [ 0.90990927,  0.07778045, -0.70233826,  0.09623805]]])

In [4]:
#dim shape size itemsize

##array function##


In [5]:
a.sum()

-3.370518275425579

In [6]:
a.sum(axis=0)

array([[-2.36254394,  0.32126055, -0.74366886, -0.62365544],
       [ 0.18370956,  0.4034755 , -1.0714935 , -0.47937453],
       [ 1.24727389, -0.4958122 , -1.37727296,  1.62758365]])

In [29]:
a=np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
a.max()

6

In [9]:
a.max(axis=0)

array([4, 5, 6])

In [13]:
a.mean()

3.5

In [11]:
a.std()


1.707825127659933

In [12]:
a.var()

2.9166666666666665

In [26]:
iqr=np.mean(a)



In [21]:
b=np.median(a)
b
#according to meand and median we check the skewness of the graph

3.5

In [30]:
q3=np.quantile(a,0.75)
q3
# for q3=75%

4.75

In [28]:
#calculate the upper range for outliner
upper_range=q3+1.5*iqr
upper_range

10.0

# MATH FUNCTIONS

In [31]:
np.sin(65)

0.8268286794901034

In [32]:
np.cos(90)

-0.4480736161291701

In [33]:
np.log(10)

2.302585092994046

In [34]:
np.log10(10)
#log and sqrt are used to reduce the skewness, log and sqrt reduces the values hence reduces the skewness

1.0

# reducing skewness

In [57]:
a=np.array([0,2,3,4,5,6,7,20,40,50,60,70])

In [37]:
b=np.mean(a)
b


22.333333333333332

In [38]:
c=np.median(a)
c

6.5

In [49]:
skew(a)

0.6957046207302622

In [50]:
a=np.sqrt(a)

In [51]:
a


array([ 0.        ,  1.41421356,  1.73205081,  2.        ,  2.23606798,
        2.44948974,  2.64575131,  4.47213595,  6.32455532,  7.07106781,
        7.74596669,  8.36660027,  8.94427191, 10.        ])

In [53]:
skew(a)

0.24994888183108938

In [54]:
y=np.random.choice(['a','b'],100)

In [55]:
np.unique(y,return_counts=True)

(array(['a', 'b'], dtype='<U1'), array([50, 50], dtype=int64))

In [58]:
np.concatenate([a,y])

array(['0', '2', '3', '4', '5', '6', '7', '20', '40', '50', '60', '70',
       'b', 'a', 'a', 'a', 'a', 'b', 'a', 'b', 'a', 'a', 'b', 'b', 'b',
       'a', 'a', 'b', 'b', 'b', 'b', 'b', 'b', 'a', 'a', 'a', 'b', 'a',
       'a', 'a', 'a', 'b', 'a', 'a', 'b', 'a', 'b', 'b', 'b', 'a', 'b',
       'b', 'a', 'b', 'b', 'a', 'b', 'a', 'a', 'a', 'a', 'b', 'a', 'a',
       'a', 'a', 'b', 'b', 'b', 'b', 'a', 'b', 'b', 'a', 'a', 'b', 'b',
       'b', 'b', 'a', 'a', 'b', 'b', 'a', 'b', 'a', 'b', 'b', 'b', 'a',
       'b', 'b', 'a', 'a', 'b', 'a', 'a', 'b', 'a', 'b', 'a', 'a', 'a',
       'a', 'b', 'b', 'b', 'a', 'b', 'a', 'a', 'b'], dtype='<U11')

# indexing and slicing

In [60]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)
b=a[:2,1:3]
b

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


array([[2, 3],
       [6, 7]])

In [63]:
a[0]

array([1, 2, 3, 4])

In [67]:
a[0,0]

1

In [70]:
c=a>2


array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [71]:
a[a>4]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [72]:
a[a%2==0]
#selecting even numbers

array([ 2,  4,  6,  8, 10, 12])

# vectorization

In [73]:
#converting a scalar into vector is called vectorization
#repeating same elements in set

In [77]:
a=np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [75]:
s=10
a+s

array([11, 12, 13])

# broadcasting

In [78]:
b=np.array([5,7])

In [79]:
a+b

array([[ 6,  9],
       [ 8, 11]])

# cross v/s dot

In [80]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])

In [81]:
a*b

array([[ 5, 12],
       [21, 32]])

In [83]:
np.dot(a,b)

array([[19, 22],
       [43, 50]])